### ISSUE TITLE
MMS/spatial/advection fails

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1007]
This tries to test the bracket operator.
However, the test produces terrible checker-boarding, which is smoothed by a forth order derivative.
The strength of the smoothing basically controlls the convergence - thus the test is in the current form imho not really useful.

Should it be removed, or does anybody wants to fix it?

**Comment by dschwoerer** [comment]
I wrote a replacement for the old test:
https://github.com/boutproject/BOUT-dev/blob/bracket_mms/tests/MMS/bracket/runtest

**Comment by bendudson** [comment]
Thanks for improving this test. 

Spatial smoothing is always needed with central differencing operators like Arakawa, in any realistic simulation. The method has little intrinsic dissipation, so needs some in order to converge if there are any modes near the grid scale. The test should converge at 2nd order, whereas the dissipation is 4th order; if the error is dominated by the dissipation then 4th order convergence would be seen.
