### ISSUE TITLE
Code hangs when jyseps2_2=0

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1024]

**Comment by johnomotani** [comment]
If jyseps2_2 is set to zero, then simulations hang during initialization when there is more than one processor in the y-direction. Specifically, the processor(s) with ``PE_YIND>0`` stop at https://github.com/boutproject/BOUT-dev/blob/b80357185dda327ba5da326544ea1e47498e05ef/src/mesh/impls/bout/boutmesh.cxx#L664 while processors with ``PE_YIND==0`` return from ``BoutMesh::load()`` and continue to https://github.com/boutproject/BOUT-dev/blob/b80357185dda327ba5da326544ea1e47498e05ef/src/mesh/impls/bout/boutmesh.cxx#L982
I think the problem might be ``comm_inner`` not being set properly, but if it is I don't know whether it's the ``PE_YIND==0`` or ``PE_YIND>0`` processors that are wrong.

I think ``{jyseps1_1=-1, jyseps1_2=0, jyseps2_1=0, jyseps2_2=0}`` should be valid input options, representing a domain in the outer divertor leg SOL, so that this is a bug.

A check that ``jyseps2_2>=jyseps2_1`` might be useful too, e.g. after https://github.com/boutproject/BOUT-dev/blob/b80357185dda327ba5da326544ea1e47498e05ef/src/mesh/impls/bout/boutmesh.cxx#L208-L213 but I don't think it fixes this issue.

**Comment by bendudson** [comment]
This is a bug,  but I think it should throw an exception rather than hanging.  The jyseps* indices are the last index in each domain,  so jyseps2_2 is the last y index in the "core" region before the outer leg. Setting it to 0 means that there is a branch cut (x-point)  between y index 0 and index 1. 

For a SOL simulation usually you should set jyseps2_2 to ny,  1_1 to -1. In the x direction set ixseps1 and ixseps2 to -1.

Sorry for this awful system. I didn't create it (blame UEDGE, or possibly some more distant ancestor), but have helped perpetuate it. Hopefully it can soon be replaced with something less archaic.

**Comment by johnomotani** [comment]
I think it might have to do with setting NXPE in the options as well. When NXPE is set explicitly, checks on whether jyseps* are valid were not done. I've copied the tests to the other case in #1025.

**Comment by ZedThree** [comment]
Fixed in #1025
