### ISSUE TITLE
linking fftw3 on Marconi

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1186]
* I'm having a problem linking fftw3 on Marconi, but only when I'm using the intel-2018 compilers instead of the default intel-2017.
* `configure` is finding the correct path to fftw3 - config.log contains the line
    ```
    PATH: /cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/bin
    ```
    but this path does not seem to be passed through to the compiler/linker as far as I can see.
* I've had to use HDF5 instead of netCDF for now because the netcdf-cxx4 module is not compatible yet, so I'm using test-io_hdf5 to show the problem.
* When I make/run the test on the login node it's fine, but when I submit it to the queue I get the error `ld: cannot find -lfftw3`.
    * If I comment out the 'make' in runtest, so the job runs with the executable built on the login node, then I get the error `./test_io: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory` instead.
    * This is odd, because the fftw3 directory `/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib` only contains libfftw3.a so test_io shouldn't be linked to a .so at all.
* If I compile manually and use -L to add the path to the fftw3 library in the link command, so run from the command line
    ````
    $ mpiicpc -I../../../include    -I/cineca/prod/opt/libraries/hdf5/1.8.18/intel--pe-xe-2018--binary/include -I/cineca/prod/opt/libraries/zlib/1.2.8/gnu--6.1.0/include -I/cineca/prod/opt/libraries/szip/2.1/gnu--6.1.0/include   -g -g -O0 -Og -fno-inline -hipa1 -DCHECK=3 -DSIGHANDLE -DLOGCOLOR -DBOUT_VERSION_STRING="\"4.1.2\"" -DBOUT_VERSION_DOUBLE=4.12  -DBACKTRACE -DHDF5 -DBOUT_HAS_PVODE  -std=c++11  -DBOUT_FLAGS_STRING=" -g -g -O0 -Og -fno-inline -hipa1 -DCHECK=3 -DSIGHANDLE -DLOGCOLOR -DBOUT_VERSION_STRING="\"4.1.2\"" -DBOUT_VERSION_DOUBLE=4.12  -DBACKTRACE -DHDF5 -DBOUT_HAS_PVODE  -std=c++11 " -c test_io.cxx -o test_io.o
    
    $ mpiicpc  -o test_io test_io.o  -lm -L../../../lib -lbout++ -lm   -L/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib -lfftw3  -L/cineca/prod/opt/libraries/hdf5/1.8.18/intel--pe-xe-2018--binary/lib -L/cineca/prod/opt/libraries/zlib/1.2.8/gnu--6.1.0/lib -L/cineca/prod/opt/libraries/szip/2.1/gnu--6.1.0/lib -lhdf5_hl -lhdf5  -lsz -lz -ldl -lm -L../../../lib -lpvode -lpvpre
    ````
    then the test runs and passes.
* I don't have the autoconf knowledge to know, but is it possible to add a '-L' for fftw3? It seems like it should be possible since configure has found the path already.

**Comment by d7919** [comment]
That shows that on the login node you're actually linking against the system version of fftw3 in `/lib64/libfftw3.so.3`. My guess would be that the marconi module isn't setting LD_LIBRARY_PATH correctly such that the module version is not being preferred, but I could be wrong.

**Comment by d7919** [comment]
Alternatively I think we probably would want to add the lib path to those used in configure/make. @ZedThree might be able to comment more.

**Comment by johnomotani** [comment]
Sorry, should have said I checked LD_LIBRARY_PATH and it looked OK - it contains `/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib`. On the login node
`
$ echo $LD_LIBRARY_PATH
`
`
/cineca/prod/opt/libraries/hdf5/1.8.18/intel--pe-xe-2018--binary/lib/:/cineca/prod/opt/libraries/petsc/3.8.3/intelmpi--2018--binary/lib:/cineca/prod/opt/libraries/zlib/1.2.8/gnu--6.1.0/lib:/cineca/prod/opt/libraries/szip/2.1/gnu--6.1.0/lib:/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/ofi/10.5/lib64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/impi/2018.3.222/lib64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/mkl/lib/intel64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/itac_latest/lib:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/inspector/lib64:/marconi_work/FUA32_SOL_BOUT/pkg/netcdf-cxx4/lib:/cineca/prod/opt/libraries/scipy/0.18.1/python--3.5.2/lib:/cineca/prod/opt/libraries/numpy/1.11.2/python--3.5.2/lib:/cineca/prod/opt/compilers/python/3.5.2/none/lib
`
and from a submitted job
`
/cineca/prod/opt/libraries/hdf5/1.8.18/intel--pe-xe-2018--binary/lib/:/cineca/prod/opt/libraries/petsc/3.8.3/intelmpi--2018--binary/lib:/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/mkl/lib/intel64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/lib/intel64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/itac_latest/lib:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/inspector/lib64:/cineca/prod/opt/libraries/hdf5/1.8.18/intel--pe-xe-2018--binary/lib/:/cineca/prod/opt/libraries/zlib/1.2.8/gnu--6.1.0/lib:/cineca/prod/opt/libraries/szip/2.1/gnu--6.1.0/lib:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/ofi/10.5/lib64:/cineca/prod/opt/compilers/intel/pe-xe-2018/binary/impi/2018.3.222/lib64:/marconi_work/FUA32_SOL_BOUT/pkg/netcdf-cxx4/lib:/cineca/prod/opt/libraries/scipy/0.18.1/python--3.5.2/lib:/cineca/prod/opt/libraries/numpy/1.11.2/python--3.5.2/lib:/cineca/prod/opt/compilers/python/3.5.2/none/lib
`

**Comment by d7919** [comment]
I guess the issue is that compilers (at least gcc) prefer shared libraries over static ones, so as we're not explicitly asking to link with the static version _and_ it can find a shared version in the standard search paths it ends up preferring that when linking the final executable. This works on the login node as we can still see this shared file, but not on the production node as the shared file is no longer accessible and fftw was linked as a shared lib. This should be fixable but will require some tweaks. Perhaps we should be explicit with the exact path to the libs we want to link given that we must know this path for configure to be successful.

**Comment by ZedThree** [comment]
Quick fix: add `LDFLAGS="-L/cineca/prod/opt/libraries/fftw/3.3.7/intelmpi--2018--binary/lib"` to your configure line.

The problem is in [`BOUT_ADDPATH_CHECK_LIB`][1] which checks if we can compile and link with a given library. It first tries to see if we can do it without any flags first, and then with just `-llib`. This is for systems like Archer that take care of everything in the compiler wrapper. It works this way in both master and next.

Unfortunately, on Marconi this works with just `-lfftw` which finds the system version, and this breaks on the compute nodes because they don't have the system libraries.

To fix this properly, `BOUT_ADDPATH_CHECK_LIB` needs to be a bit cleverer. The quick fix above will work though.

[1]: https://github.com/boutproject/BOUT-dev/blob/next/m4/bout.m4#L37
