### ISSUE TITLE
Examples that don't compile

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1457]
It seems that both `non-local_1d` and `test-difops` rely on aspects of BOUT++ that no longer exist (and were possibly experimental). Should we retire/remove these examples or seek to update to be compatible with recent BOUT++ versions (if this is even possible)?

**Comment by dschwoerer** [comment]
I think it was there to demonstrate a technique, and that technique has been removed, the example can go.

**Comment by d7919** [comment]
I agree we shouldn't have examples for things that don't exist currently! I just wasn't sure if these examples were demonstrating the use of the things that have been removed or that the use of those things was just for convenience. @johnomotani may know if some of these should still be supported.

**Comment by johnomotani** [comment]
The model implemented in `non_local_1d` only works for small amplitude perturbations in a slab, so I'm not keen on putting effort into maintaining it. If it was going to be maintained, it should probably be a separate repo under `boutproject`. It also used special communication methods because it needed to overlap lots of integrations in the y-direction, which have been removed (that's why it doesn't compile any more, if I remember right). I'm in favour of removing `non_local_1d` from BOUT-dev. I'll archive it to a separate repo; I wouldn't keep it in `boutproject` though as it's not active.

**Comment by dschwoerer** [comment]
If you remove it, and have a clear commit message, it is probably even easier to get, then having to find a separate repository.
I don't think having repository with broken stuff is particularly useful, as it hides other, non-broken projects. With git nothing is ever lost (unless you force-push)

**Comment by dschwoerer** [comment]
Close as the mentioned examples are removed
