### ISSUE TITLE
17/18 tests fail in test_suite

### ISSUE THREAD

**Issue by aratava** [boutproject/BOUT-dev#1461]
I followed the documentation for installing BOUT 4.0.0 several times. I could make it run once but after I added SUNDIALS the things went wrong again and I couldn't solve the problem, after that. Although I removed everything and tried to install everything from scratch, the problem persists. 17/18 tests fail in test_suit and when I run ./conduction example, I get an error:

_error while loading shared libraries: libhdf5.so.101: cannot open shared object file: No such file or directory_

my machine characteristics are:
Ubuntu 18.04.1 LTS
Intel® Core™ i7-8700 CPU @ 3.20GHz × 12 

The make.config file and one of the run.log.* files are attached.

[files.zip](https://github.com/boutproject/BOUT-dev/files/2684093/files.zip)

Thank you in advance

**Comment by d7919** [comment]
My guess is that when you've configured it has picked up some shared hdf5 libraries in your anaconda install that aren't generally available in the library path so that when you try to run you see this error. If I'm correct then a bit of a workaround would look like 

`export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/atavassoli/anaconda3/lib`

before then running the example.

**Comment by aratava** [comment]
Thank you so much David. Yes you were right. After adding this line to the bashrc the problem solved.
