### ISSUE TITLE
pdf version of manual not present on readthedoc

### ISSUE THREAD

**Issue by jtmalos** [boutproject/BOUT-dev#1565]
I was interested in the pdf version of the manual however it doesn't appear to be available at https://bout-dev.readthedocs.io/en/latest/

I've also attempted to build the manual on Ubuntu 18.04 using a manual install of texlive2018 but without success. My current issue is that latex is failing on BOUT.tex complaining of series of undefined control sequences. Ignoring these finally generates a 743 page manual but I would like to resolve why there are a few pages that are failing the latex compile. Is it possible that the pdf version hasn't been built for a while and that the manual file is not compatible with texlive 2018 (?) If so could someone confirm which version of latex should be used to compile? Thanks.

**Comment by d7919** [comment]
I think we moved our documentation from Tex to rst to support the move to readthedocs so I'm not sure if the Tex form builds correctly anywhere and is probably out of date. We can enable pdf builds on readthedocs in principle but there may be a reason why we didn't (I seem to recall some resource limitation), @ZedThree set this up so may recall any reason.

**Comment by dschwoerer** [comment]
Maybe we should add a travis job, to ensure the manual can be build?
With doxygen any code change can break the pdf. I remember once an empty line was the cause ...

I removed the pdf build a while ago from the [copr release](https://copr.fedorainfracloud.org/coprs/davidsch/bout) because it kept getting broken.

**Comment by jtmalos** [comment]
Thanks very much for the replies and info. At least I know it's not (necessarily) something I'm missing.
There are definitely issues with doxgen-related auto-generated latex (via python-breathe). However I forgot to mention that my main interest in the pdf manual is to read this offline to understand how to use bout++. As such I wouldn't need the auto-generated API sections at that stage, and would instead refer to the html documentation when using bout.

However even after disabling breathe, there are a couple of remaining latex undefined control sequences in the body of the manual (generated from coordinates.rst). They look just like some boldfont control so skipping has virtually no impact on the final manual that's generated. It's useful enough to now use offline. Thanks again.

**Comment by dschwoerer** [comment]
Note you can also use the html version offline.

`make manual-html` should build that. It should print at the end some html file, which you can open in you browser - all of which should work offline.
You could also build a man page, but man pages have some restriction, and are imho not that great to read ...

**Comment by ZedThree** [comment]
I originally disabled the PDF builds because we were hitting the resource limits on readthedocs, but I did put some effort in a while ago to reduce how much time/memory we were using. We're now well under the time limit at least, so I've re-enabled the PDF builds.

If you're reading through the documentation, it would be lovely if you could raise issues for things you think could be improved! I'm not promising they'll get fixed quickly, but it would be good to know what isn't clear :)
