### ISSUE TITLE
master is broken with gcc 8

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1572]
I think we just need to provide `swap(Coordinates&, Coordinates&)`. I'm not really sure how this compiled to begin with.

```make
In file included from ../../include/bout/coordinates.hxx:38,
                 from coordinates.cxx:9:
../../include/bout/mesh.hxx: In member function ‘void Mesh::recalculateStaggeredCoordinates()’:
../../include/bout/mesh.hxx:463:77: error: no matching function for call to ‘swap(std::__shared_ptr_access<Coordinates, (__gnu_cxx::_Lock_policy)2, false, false>::element_type&, std::__shared_ptr_access<Coordinates, (__gnu_cxx::_Lock_policy)2, false, false>::element_type&)’
       std::swap(*coords_map[location], *createDefaultCoordinates(location));
                                                                           ^
```

EDIT: Actually we don't even need `swap`, just a copy ctor or `noexcept` move ctor will do

**Comment by d7919** [comment]
I thought as all members have a defined swap this should hiding swap each individual member (like certain default methods), but I may well have misunderstood something

**Comment by d7919** [comment]
Any idea why it works with 7 and older (and clang)?

**Comment by johnomotani** [comment]
This looks like the same issue I had on #1548? That problem seemed to be fixed by moving the implementation of `recalculateStaggeredCoordinates` to the .cxx file. My guess is that then `Coordinates` is a complete type, so the compiler knows it has a copy constructor (the default one) and `std::swap` can work. Don't know why the original version works on older compilers though!

**Comment by ZedThree** [comment]
Yes, I think you're right. This comes about due to the inclusion of `mesh.hxx` in `coordinates.hxx`. A forward declaration of `class Mesh` in `coordinates.hxx` also fixes things.
