### ISSUE TITLE
Tests fail with openmpi 3

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1582]
OpenMPI 3 doesn't like oversubscribing, according to [SO](https://stackoverflow.com/a/40044717) which can be "fixed" by passing `--oversubscribe`.

Having tried with openmpi 2, 3 and mpich 3, it seems the option has only a single dash `-oversubscribe`, and both versions of openmpi are happy with it, while mpich doesn't like it (error parsing argument).

I would think we need to distinguish which mpi version we have, and depending on that, add `-oversubscribe`
Another option would be to tell the user they need to do that, but I would prefer if we could do that ...

**Comment by ZedThree** [comment]
I'm not keen on trying to automatically detect what version of MPI we're using, because it ends up being very fragile.

I've reviewed a few different open source projects and how they handle this problem, and they basically all just set:
```shell
export OMPI_MCA_rmaps_base_oversubscribe=yes
```
This shouldn't affect other MPI implementations.

I'm not sure the best place for this. Either `run_wrapper.getmpirun` or `run_wrapper.launch`, possibly. Or just as an environment variable on Travis.

Users can always just set that environment variable themselves, or set `MPIRUN` to include the appropriate flag.
