### ISSUE TITLE
Possible bug in Solver::pre_rhs?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1657]
In `Solver::pre_rhs`, we apply boundary conditions to the fields at the current simulation time:

https://github.com/boutproject/BOUT-dev/blob/1c8d7699c096a98dd28af393bd1ac32e4ffec6af/src/solver/solver.cxx#L1251-L1262

However, we don't actually have a `Field2D::applyBoundary(BoutReal)`, so it gets resolved to `Field2D::applyBoundary(bool)`:

https://github.com/boutproject/BOUT-dev/blob/1c8d7699c096a98dd28af393bd1ac32e4ffec6af/include/field2d.hxx#L266

I'm pretty sure that's not what we intend to do here.

**Comment by bendudson** [comment]
Strange that there's no time argument version of this for `Field2D`. I guess `Field2D` are not evolved often enough (or ever?) for this to be noticed before.

1. Yes it looks like a `Field2D::applyBoundary(BoutReal)` method is needed,

and

2. Is there some way to catch these crazy casts, like silently converting almost anything (it seems) to a bool? An answer here (https://stackoverflow.com/questions/175689/can-you-use-keyword-explicit-to-prevent-automatic-conversion-of-method-parameter) recommends making a private templated version to disable casting.

**Comment by ZedThree** [comment]
Another possibility is to `= delete` unwanted overloads

**Comment by johnomotani** [comment]
I was a bit confused by the `apply_to_ddt` conditional in `applyBoundary(bool)`. I think `apply_to_ddt` is actually redundant now: it's not checked in `applyBoundary(BoutReal)` and I think this is correct, because now the boundary conditions have both `apply(BoutReal)` and `apply_ddt(BoutReal)` and one or the other will be a no-op. Maybe we should remove it?
