### ISSUE TITLE
Bug in interpolating zShift

### ISSUE THREAD

**Issue by friva000** [boutproject/BOUT-dev#1742]
When using shifted grids, if zShift is not provided in the grid file on the shifted coordinate, the code read zShift from the grid file on CELL_CENTRE and interpolates it on the shifted coordinate. However, the interpolation is wrong.

In fact, when initializing the CELL_CENTRE coordinate object, the code read it from the grid file, interpolates it in the guard cells (if necessary), and correct the guard cells at the branch cut (using ShiftedAngle). On the other hand, for the interpolation, it is just used the zShift from the grid file, without correcting the guard cells at the branch cut and at the targets.

I think that it would be better to have a method to get zShift from a paralleltransform object (like `coord_centre->getParallelTransform().getzShift()`) and use this zShift for the interpolation, instead than reading again zShift from the grid file to obtain it at CELL_CENTRE.

**Comment by ZedThree** [comment]
I would be very wary about putting a `getzShift` method into the base `ParallelTransform`, as it's only relevant for `ShiftedMetric`. 

Perhaps I'm being dim, but in `Coordinates::setParallelTransform` there's a comment that sounds like it's doing what you say:

https://github.com/boutproject/BOUT-dev/blob/79e7b48c7dbf0570356b7a236770ccc7b617b312/src/mesh/coordinates.cxx#L1121

That looks like it's being done for any location.

**Comment by friva000** [comment]
For the `getzShift` method it could be a virtual method that throws if not `ShiftedMetric`... But if you have better solutions, it would be great.

You're right in saying that the guard cells are corrected. The problem is at https://github.com/boutproject/BOUT-dev/blob/79e7b48c7dbf0570356b7a236770ccc7b617b312/src/mesh/coordinates.cxx#L1115

The code computes `zShift` at `CELL_CENTRE`, with corrected guard cells. When it computes `zShift` for a shifted grid, instead of using the computed `zShift`at CELL_CENTRE, it does

https://github.com/boutproject/BOUT-dev/blob/79e7b48c7dbf0570356b7a236770ccc7b617b312/src/mesh/coordinates.cxx#L1107

which means that it is using the `zShift` at `CELL_CENTRE`, but without the correct guard cells.

**Comment by johnomotani** [comment]
I've started working on a fix in https://github.com/boutproject/BOUT-dev/tree/staggered-zshift-fix

I think I've gone around Peter's concern about the method there (by luck rather than judgement). I've taken the approach of just making `zShift` a public member of `ShiftedMetric` so that `Coordinates::setParallelTransform` can, in the bit constructing a staggered `ShiftedMetric`, cast the cell-centre `ParallelTransform` to a `ShiftedMetric` and access `zShift` directly. I think the cast is OK in this instance, as `Coordinates::setParallelTransform` is effectively the 'factory' for `ParallelTransform`s and we know we're in the `ShiftedMetric` branch at the point where the cast is done.

@ZedThree @friva000 what do you think?

**Comment by friva000** [comment]
As long as it is not a problem having a public zShift, I agree it is the best solution.

**Comment by ZedThree** [comment]
Is the easy fix not just

```diff
+       Field3D zShift_centre;
-       if (localmesh->get(zShift, "zShift")) {
+       if (localmesh->get(zShift_centre, "zShift")) {
          // No zShift variable. Try qinty in BOUT grid files
-         if (localmesh->get(zShift, "qinty")) {
+         if (localmesh->get(zShift_centre, "qinty")) {
            // Failed to find either variable, cannot use ShiftedMetric
            throw BoutException("Could not read zShift"+suffix+" from grid file");
          }
        }

-       zShift = interpolateAndExtrapolate(zShift, location);
+       zShift_centre = interpolateAndExtrapolate(zShift_centre, CELL_CENTRE);
+       zShift = (location == CELL_CENTRE) ? zShift_centre 
+                : interpolateAndExtrapolate(zShift_centre, location);
      }
```
?

A bit more work, sure, but this should only be done once per simulation.

Otherwise, @johnomotani 's approach is ok, although I'd use getter for `zShift` rather than just making it public (as there's an invariant -- changing `zShift` means recalculating all the phases), but don't put the getter in the base class as it's not meaningful for the other transforms.

**Comment by johnomotani** [comment]
@ZedThree - trouble is we need the branch-cut fix as well. Still, if we wrap up the 'guard cell fixing' into a function, we can apply it to `zShift_centre` rather than adding a getter to `ShiftedMetric` and then we don't have to change the interface.
