### ISSUE TITLE
Differential operators at grid indices

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#185]
The differential operator code in sys/derivs.cxx and mesh/difops is probably over-complicated and not particularly efficient. It contains loops over the domain using the old Stencils/bindex code, and more pointer indirections than is perhaps ideal in inner loops. Some of this is to allow flexibility, such as changing numerical method in the input file, but this makes optimisation difficult. What I'd like (in the "next" branch) is:
1. Operators which are flexible when needed, but can be hard-wired and optimised with minimal changes. At the moment a specific method can be specified in the code using a method argument e.g. DDX(f, DIFF_C2) but this doesn't allow the compiler to optimise much since a function pointer lookup is still needed. Instead, something like
   
   result = DDX(f) ; // General method, can be switched in input
   result = DDX_C2(f); // Function (possibly inline) with fixed method, avoiding options and function pointer lookup
2. A way to make more efficient use of cache, by reducing the number of loops over the domain. One way to do this might be to have operators which work on a single index at a time e.g.

BoutReal Div_par(const Field3D &f, const DataIterator &index);

to allow RHS functions to be written as something like:

for(auto i : ddt(Ne)) {
    ddt(Ne)[i] = -bracket(phi, Ne, i) - Div_par(NVi, i) + Source[i];
}

note the extra index (i) argument to bracket and Div_par operators. This would have only one loop over the domain, rather than the 4 or 5 used in the equivalent expression:

ddt(Ne) = -bracket(phi, Ne) - Div_par(NVi) + Source;;

Does this sound like a sensible enhancement?

**Comment by bendudson** [comment]
Test case to try out this in examples/performance/difops/test-difops.cxx added in commit 2f3eeaa10

**Comment by dschwoerer** [comment]
I really like the option with the [] argument - in case I want the derivative only e.g. in the boundary - that would allow me to do this efficiently.

I have been thinking whether it might be possible to write a script (e.g. python) to generate all possible derivatives, so that DDX_C2_non_staggered and similar variants can be without non inlined, internal function calls.

The applyXDiff can then still do a lookup to see which of those functions it needs to use, but the call it self could be very well vectorised.

I got a nice speedup by writing the derivative code without function calls, [see here](https://github.com/dschwoerer/BOUT-dev/blob/fastdiff-cleaned/src/sys/derivs.cxx#L1234)
but doing it by hand seems like a bad choice ...

**Comment by bendudson** [comment]
This seems like a good suggestion, to have the function call on the "outside" rather than the inner loop. The downside is that the same operators can't be applied in multiple directions, and there would need to be separate operators for Field2D and Field3Ds (unless templates are used).

The functions could be arranged something like:

inline BoutReal DDX_C2(const Field3D &f, const DataIterator &i);

const Field3D DDX_C2(const Field3D &f);   // Loops over domain, maybe calling inline function above

const Field3D DDX(const Field3D &f);  // Does method switch, calls DDX_C2(f) or other function

A lot of typing could be saved by using templates or macros

**Comment by bendudson** [comment]
The differential operator implementation has been reworked multiple times, and there are now "single index operators" for moving loops to the outside.
