### ISSUE TITLE
PETSc installation advice in docs is outdated

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#2026]
https://bout-dev.readthedocs.io/en/latest/user_docs/advanced_install.html#petsc

- While we sort of support PETSc 3.4+, we definitely recommend 3.7+, and we should recommend using the latest available version
- The advice to tell PETSc to use a pre-compiled version of SUNDIALS is not great; we should recommend either using a standalone SUNDIALS or compiling PETSc with `--download-sundials` but not both

**Comment by johnomotani** [comment]
I think our advice should be that even if you configure with SUNDIALS, PETSc does not need to be linked to SUNDIALS. I believe the only reason to link PETSc to SUNDIALS would be to call SUNDIALS time-solvers via the PETSc interface: I don't think the PETSc time-solver interface in BOUT++ is widely used, and even if it is used I doubt there is a benefit to calling the SUNDIALS solvers through PETSc rather than directly. If a user really wants PETSc linked to SUNDIALS for some reason, I think it's fair to assume that they're sufficiently expert to decide how to link it themselves.
