### ISSUE TITLE
Is there a 1D data structure equivalent to Field3D ?

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#208]
This is needed if you have a 1d field being a function of e.g. x, since the x-direction is usually domain decomposed.

**Comment by dschwoerer** [comment]
There is afaik no Field1D - furthermore I am not sure whether calling it `Field1D` would be beneficial, as e.g. I would need it rather in y direction.

I am not sure what you need it for - but if you don't care about performance, you can maybe use a `Field3D` and set it to `x`:
```
  Field3D x = FieldFactory::get()->create3D("x", NULL, mesh, CELL_CENTRE, 0);
  Field3D y = FieldFactory::get()->create3D("y", NULL, mesh, CELL_CENTRE, 0)/TWOPI ;
  Field3D z = FieldFactory::get()->create3D("z", NULL, mesh, CELL_CENTRE, 0)/TWOPI ;
```

**Comment by bendudson** [comment]
Not really, unfortunately. In the X direction parallelisation is relatively easy because there are no branch cuts in the X direction. In the y direction there are more issues due to branch cuts. The cyclicReduction solver has logic for dealing with this. 

I think a few use cases would help in designing improvements to the mesh. Before adding anything like this, I'd like to think about how to consistently define slices. For example Field2D is constant in its 'missing' dimension Z, but FieldPerp is a slice at a single Y location. Should Field1Ds (whatever they're called) be constant in the other 2 dimensions, or at fixed coordinates? There are probably use cases for both possibilities.

-------- Original Message --------

**Comment by JensMadsen** [comment]
Ok. 

I guess that I someone decide to implement such data structures it might be a good idea to make the names more descriptive e.g. Field2D_XY ?

**Comment by d7919** [comment]
The Array, Matrix and Tensor classes allow 1D/2D/3D storage but don't provide some of the nice Field behaviour. They may be enough for some things though.
