### ISSUE TITLE
compiling BOUT++ on Marconi 

### ISSUE THREAD

**Issue by gregordecristoforo** [boutproject/BOUT-dev#2110]
I tried to install BOUT++ on Marconi myself and received an error:

...
configure: *** Now run 'gmake' to compile BOUT++ ***
gdecrist@r000u06l01:~/BOUT-dev$ gmake
Downloading mpark.variant
You need to run this command from the toplevel of the working tree.
gmake[2]: *** [/marconi/home/userexternal/gdecrist/BOUT-dev/externalpackages/mpark.variant/include/mpark/variant.hpp] Error 1
gmake[1]: *** [field] Error 2
gmake: *** [src] Error 2

Running "git submodule update --init --recursive" fixes this issue. Is this a bug or did I make a mistake myself?

**Comment by ZedThree** [comment]
Hi Gregor, this is almost certainly our fault, not yours! :) Which version or branch are you using?

**Comment by gregordecristoforo** [comment]
Hi Peter, I tried both the master and the v4.3.0-rc branch and received the same error.

**Comment by dschwoerer** [comment]
I am having troubles reproducing this - could you mention what command you used to invoke `./configure`?

**Comment by gregordecristoforo** [comment]
I simply run `./configure` without specifying anything in addition.

**Comment by johnomotani** [comment]
I've never understood why sometimes the submodules complain and sometimes they update fine. Reproducing is a pain because `git submodule update --init --recursive` always seems to fix the issue, and configure/make are fine afterwards - I guess that means the problem depended on the state the repo and/or submodules were in before, which I guess would depend on the history of what was checked out or cloned and in what order...

**Comment by johnomotani** [comment]
Maybe we should have a 'troubleshooting' section in the manual? For this case - if `mpark.variant` or other submodules give errors, try `git submodule update --init --recursive`. I'm sure there are other common errors that BOUT gives that we could collect solutions for!

**Comment by dschwoerer** [comment]
Does #2107 help in that case?
It moves the submodule-checkout to configure, where we are in $BOUT_TOP - or is the issue rather related to giving the path to `git submodue`?

**Comment by johnomotani** [comment]
> Does #2107 help in that case?

I think it might do.

In what is probably a separate issue (sorry I don't remember more details, I've got in the habit of just running `git submodule update --init --recursive` whenever there's a problem and then forgetting about it again...), it looks like #2107 makes `configure` check if `externalpackages/mpark.variant/include` exists. Sometimes there is a problem because the version is wrong (e.g. switching between `master` and `next` if I recall correctly). It might be nice to also check if the downloaded `mpark.variant` is the correct version (i.e. would `git submodule update --init --recursive` do anything or not?). Don't know if there's a nice test for that?

**Comment by ZedThree** [comment]
I couldn't reproduce this either, so I wonder if it's due to a combination of `git` and/or `make` versions?

@johnomotani That issue when switching branches can usually be avoided if you set `git config --global submodule:recurse=true`

This is something that CMake seems to handle fine, but it could just be it's fine on my system and has exactly the same issues on other people's.

**Comment by johnomotani** [comment]
I'll try and remember to make a note of what I was doing if it comes up again...
