### ISSUE TITLE
Is there a way to specify geometry in the BOUT.inp file?

### ISSUE THREAD

**Issue by AlxMar** [boutproject/BOUT-dev#215]
I mean, to specify metric tensor coefficients there. If it is possible, can someone give an example, please. For ex., for a cylindrical mesh.

**Comment by JensMadsen** [comment]
Hi Alexander 

You can specify the metric tensor in three ways

1) in the BOUT.inp file in the [mesh] section
2) In the init method e.g.: mesh->g11 = 1.0;
3) in a grid file

In the examples folder you will find several examples of either approach. 

Good luck

**Comment by JensMadsen** [comment]
I do not think that your approach will work:-d sorry

Try to take a look at 

BOUT-dev/examples/MMS/diffusion2

This will give you an idea of how you solve the diffusion equation in BOUT++  and how you should deal with metric coefficients, grid spacing etc. I suggest that you understand this example and do your own afterwards. Feel free to ask more questions:-D

**Comment by AlxMar** [comment]
Ok, I see. But in this example everything is uniform and Cartesian coordinates used. So, I will continue playing with it.
I have just realized I need to use g_22 instead of g22, for covariant form.

**Comment by JensMadsen** [comment]
I think that non-equidistant meshes are still somewhat experimental

**Comment by bendudson** [comment]
Hi Alexander,

This method should work, specifying the metric components in the BOUT.inp
file ([mesh] section). Non-uniform meshes are taken account of in some
operators, but not in others, so as Jens says you have to be a little
careful. In several places there are settings called (inconsistently)
non_uniform or nonuniform which when turned on add corrections for
nonuniform meshes. If you search the BOUT.log.* files you should be able to
find them, and see what they are set to.

g22 would be the metric in the y direction (Grad y dot Grad y) : the
numbering (1,2,3) corresponds to (x,y,z). Is y (the coordinate parallel to
B) supposed to be the azimuthal direction, or along the axis of the
cylinder?

A typical cylindrical setup is for a linear plasma device, with y down the
axis (long direction) and z the angle coordinate around the azimuthal
direction. For this I think you could use something like

nx = 20
ny = 16
nz = 32

Ly = 1     #  Length of the cylinder

Rmin = 1e-2    # Radius at minimum in x
Rmax = 2.5e-1 # Radius at maximum in x

Rxy = Rmin + (Rmax - Rmin)*x  # Here x is normalised from 0 to 1, uniform
in grid number
dr = (Rmax - Rmin) / (nx - 4)

Bxy = 1  # Magnetic field strength

dx = Bxy * Rxy * dr  # Flux
dy = Ly/ny
dz = 2*pi / nz

g11 = (Bxy * Rxy)^2   # (Grad x)^2
g22 = 1     # Because dy = Ly/ny, no scaling needed
g33 = Rxy^2

J = Bxy  # Jacobian

# Coordinates are orthogonal
g_11 = 1 / g11
g_22 = 1 / g22
g_33 = 1 / g33

NB: I have just made this up, not tested it. Remember to also normalise the
dimensions correctly if your model is not in SI units.

Best

Ben

**Comment by AlxMar** [comment]
Hello Ben,

Thank you, this is very helpful! Yes, Y along axis is perfectly fine, especially because Z is only periodic, so it's better to use for angle.

I have implemented a simple heat equation in 2D (X,Z), just need to compare to analytical result, but [looks](https://drive.google.com/open?id=0Bw4yOQXNF6qNQzYzdWI5UUtNcGs) fine.

**Comment by AlxMar** [comment]
Update:
to use this setup we need also to add
_non_uniform = true_ 
in the "BOUT.inp".

I have some question, there is a simpler cylindrical metric that works:
_g11 = 1,   g22 = 1,   g33 = 1/r^2_,
if  (X, Y, Z) are (R, Z, PHI)
How do I know that X should be R? I wanted Y to make R, but it didn't work.

My approach was as follows. I want magnetic field  B to be along  r, everything straight, simply cylindrical. So psi ~ z, right? It will give 
B = (Grad x) x (Grad phi) = e_z  x  1/r e_phi = 1/r e_r    (e_r  is unit vector along r)
Such a magnetic field will satisfy  div B = 0. So the setup shall look like:

nx = 20
ny = 16

MZ = 17
zmin = 0
zmax = 1   # full 2*pi angle

Rmin = 1e-2    # Radius at minimum in x
Rmax = 2.5e-1 # Radius at maximum in x

Rxy = Rmin + (Rmax - Rmin)*y/(2*pi)   # as y is normalized from 0 to 2*pi 

dx = Lz/(nx-4) # cylindrical Z-coord.
dy = dr  # cylindrical R-coord.

g11 = 1.0
g22 = 1.0
g33 = 1/Rxy^2

J = Rxy

# Coordinates are orthogonal
g_11 = 1 / g11
g_22 = 1 / g22
g_33 = 1 / g33



Such a setup is not producing a correct result, I was checking with a heat equation for (r,phi) plane. And I really cannot see why.

**Comment by AlxMar** [comment]
Problem solved, just psi = Rmax / (2pi) z, so 
g11 = (Rmax/2/pi)^2
g22 = 1,
g33 = 1/Rxy^2
and that would be (z,r,phi) cylindrical coord.

**Comment by bshanahan** [comment]
I think this can be closed now?
