### ISSUE TITLE
currents in conductors

### ISSUE THREAD

**Issue by amircogan** [boutproject/BOUT-dev#2195]
Dear,

We would very much like to use BOUT for special plasma simulations.
We are trying to combine currents in conductors as well as plasma in a chamber. We also need to use a cylindrical geometry or some way of creating a 3D cylinder in a cartesian geometry.
Can these 2 be fulfilled with BOUT. If not we may want to contribute the parts that do this , but may need a bit guidance. 
Thank you in advance
   Amir

**Comment by bendudson** [comment]
Hi Amir,
- Cylindrical geometry can definitely be done, or 3D Cartesian. A limitation is that currently the "Z" dimension is assumed to be periodic, typically the toroidal angle, while the B field in many operators (for Clebsch-type coordinates) is assumed to be in the e_y direction. This works fine for a linear device, where the y direction can be down the long axis of the machine, but in cylindrical coordinates in a torus, where the axis of the coordinate system is in the vertical direction (rather than toroidal), BOUT++'s y direction is in the toroidal direction, and Z is the vertical coordinate. With Z being periodic by default, this makes imposing boundary conditions at top and bottom of the device awkward (but still possible).
- For combining plasma field and external currents, this is mainly a matter of setting up the model equations. It is certainly possible to write `A_|| = A_||,plasma + A_||,external`, calculate `A_||,plasma` from the plasma currents, and impose an `A_||,external`. External currents which respond to changes in the plasma (e.g. induced currents in wall components) is much more difficult, and custom code would need to be written to do that.

This model may do at least some of what you are looking for: https://github.com/boutproject/merging-filaments

- It is in cylindrical geometry. This is done by setting the metric coefficients: https://github.com/boutproject/merging-filaments/blob/master/toroidal-breakdown/BOUT.inp#L51
- The magnetic field is the sum of the plasma and external conductor contributions: https://github.com/boutproject/merging-filaments/blob/master/merging-flux.cxx#L216 , where Apar is the time-evolved A_|| due to the plasma
- To include the field from external coils, a custom Greens function for a unit current in a circular coil was added to the input parser https://github.com/boutproject/merging-filaments/blob/master/merging-flux.cxx#L75 . This creates a "coil_greens" function which is used in the input to define time-varying external fields: https://github.com/boutproject/merging-filaments/blob/master/toroidal-breakdown/BOUT.inp#L124

If you want to be added to the BOUT++ Slack channel please let us know
