### ISSUE TITLE
Field3D and Vector3D (probably field2D as well) do not allocate memory when variables defined

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#220]
Example

Field3D hest; 
hest(0,0,0) = 0.; 

gives an error whereas 

Field3D hest; 
hest = 0.;
hest(0,0,0) = 0.; 

or 

Field3D hest; 
hest.allocate();
hest(0,0,0) = 0.; 

do not. Is this intentional?  Perhaps call allocate() in the default constructor and set the value to 0.?

**Comment by bendudson** [comment]
This is intentional for two reasons:

1) Partly its for optimisation, so memory is not allocated or initialised
unless needed. If someone wants to make sure it's initialised they can use
Field3D hest(0.0);

2) The main reason is for initialisation. Many models have Field3D objects
as global variables, which are created before main() is run, before the
mesh exists and has a size. An allocation in the constructor would
therefore not know how large the array should be.

One possibility would be to try and allocate, and in the constructor test
if mesh exists and has a size. This could then not allocate global fields,
but would allocate fields which were created later when the mesh already
exists. Unfortunately I don't think there is any guarantee about the order
in which global variables are initialised, so trying to set the mesh to a
null pointer to indicate not existing wouldn't work.

Another way might be to have a flag to the constructor which explicitly
disables allocation, making allocation and initialisation to zero the
default. This is appealing, being safe by default, but would then result in
segfaults (before main()) if a user created a global field but forgot to
turn off allocation.

Eventually I would like BOUT++ to be able to have multiple meshes, so a
field would have to be defined over a mesh. This can be done already; the
Field3D constructor in next can take a Mesh pointer, but if not provided
then it falls back on the global default.

**Comment by JensMadsen** [comment]
Ok. I thought so :-D

Lets close this issue then ?

**Comment by JensMadsen** [comment]
Would it be ok If wee added a similar constructor to vector3D? i.e. 

Vector3D hest(0.0);
and 
Vector3D hest(0.0,1.,2.);

**Comment by bendudson** [comment]
I guess this is probably something which needs to be clarified in the manual, so maybe keep this open until the manual is updated


-------- Original Message --------

**Comment by bendudson** [comment]
This is now documented in the manual
