### ISSUE TITLE
Issue with BOUT-dev make-check on marconi

### ISSUE THREAD

**Issue by TGheorghiu** [boutproject/BOUT-dev#2293]
I am attempting to install BOUT++ to my $HOME directory on marconi, following the guide [here](https://bout-dev.readthedocs.io/en/latest/user_docs/installing.html#).

As it is on marconi, I am also using the advanced installation guide [here](https://bout-dev.readthedocs.io/en/latest/user_docs/advanced_install.html)(with intel compilers), and have apparently successfully run "./config", removed the references to -lnetcdf in bin/bout-config & make.config as instructed in the advanced install, and apparently successfully run "make" following that. 

The make check process seems to fail with error 1 and 2 as following: 

> Linking tests
ld: warning: libhdf5_hl.so.100, needed by /cineca/prod/opt/libraries/netcdf/4.6.1/intelmpi--2018--binary/lib/libnetcdf.so.13, may conflict with libhdf5_hl.so.8
ld: warning: libhdf5.so.103, needed by /cineca/prod/opt/libraries/netcdf/4.6.1/intelmpi--2018--binary/lib/libnetcdf.so.13, may conflict with libhdf5.so.8
ld: ../../lib/libbout++.a(h5_format.o): undefined reference to symbol 'H5P_CLS_DATASET_CREATE_ID_g'
ld: note: 'H5P_CLS_DATASET_CREATE_ID_g' is defined in DSO /cineca/prod/opt/libraries/hdf5/1.10.4/intelmpi--2018--binary/lib/libhdf5.so.103 so try adding it to the linker command line
/cineca/prod/opt/libraries/hdf5/1.10.4/intelmpi--2018--binary/lib/libhdf5.so.103: could not read symbols: Invalid operation
make[1]: *** [serial_tests] Error 1
make: *** [check-unit-tests] Error 2

And I am unsure as to what is going on here, as I had previously this week successfully installed BOUT++ and tested it on my $HOME directory on marconi (this is a fresh install).

attached is the make.config file, with .txt appended 
[make.config.txt](https://github.com/boutproject/BOUT-dev/files/6359294/make.config.txt)

and below are the currently installed modules I am working with:
![Screenshot_2021-04-22_16-02-18](https://user-images.githubusercontent.com/68959951/115737563-29f71000-a384-11eb-820d-72f253708b97.png)

**Comment by ZedThree** [comment]
Hi @TGheorghiu !

The issue is that the compiler is trying to link against a different version of HDF5 than the one netcdf uses. There are a few different reasons why this might happen, so we need a little bit more information. What I suspect has happened is that it's picked up a system version of HDF5, rather than the one in the modules.

Please could you upload `config.log`? This should give us the information needed to see what's happened.

**Comment by TGheorghiu** [comment]
Hi ZedThree, 

Attached is the config.log as requested. Thanks!

[config.log](https://github.com/boutproject/BOUT-dev/files/6359580/config.log)

**Comment by ZedThree** [comment]
Yep, it looks like it's picking up the system HDF5, rather than the module one.

`configure` checks for `h5cc` and uses that to determine how to link against HDF5. I guess the module might not provide this. You can provide the path yourself with `--with-hdf5=<path>` but I think it will still be looking for `h5cc` -- and you also need to know the correct path anyway!

If you do `module help hdf5/1.10.4--intelmpi--2018--binary`, it should display a short help message telling you what variables it sets. There should hopefully be one called something like `HDF5_DIR` or `HDF5_PATH`

@johnomotani Have you come across this issue?

**Comment by TGheorghiu** [comment]
Ok, as suggested I ran `./compile --with-hdf5=/cineca/prod/opt/modulefiles/base/libraries/hdf5/1.10.4--intelmpi--2018--binary` and indeed it still requests a path to h5cc.

The `module help hdf5/1.10.4--intelmpi--2018--binary` command returns the below:

![hdf5help](https://user-images.githubusercontent.com/68959951/115747862-8dd20680-a38d-11eb-8061-c4f7f2b71cd4.png)

which does not appear to be particularly illuminating in this regard

**Comment by ZedThree** [comment]
Is there a `bin` directory under `/cineca/prod/opt/modulefiles/base/libraries/hdf5/1.10.4--intelmpi--2018--binary`? It might have `h5pcc` which would also work I think

**Comment by johnomotani** [comment]
I think I've worked around this issue in the past by just compiling without HDF5 (i.e. passing `--without-hdf5`) - somehow linking via netcdf was OK. Good to know it might have been because of finding the wrong `h5cc`.

**Comment by TGheorghiu** [comment]
> Is there a bin directory under /cineca/prod/opt/modulefiles/base/libraries/hdf5/1.10.4--intelmpi--2018--binary? It might have h5pcc which would also work I think

It does not seem to be a directory, nor can I find a bin in the local area. I will do what @johnomotani suggests, and see if things work then.
