### ISSUE TITLE
Derivatives: free boundary - Issues if MXG not 2

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#250]
I've been looking at https://github.com/boutproject/BOUT-dev/blob/next/src/mesh/index_derivs.cxx#L1064

Not sure I understand what the code is doing, but it seems to me it is causing issues, if the number of xguards is not equal to 2.

If mxg == 1 wouldn't it overwrite the value of the guard cell with the one designated for the second guard cell?

And in the case of mxg == 0 the could overwrite the last point in the actual domain with a value computed for the point outside the domain?

**Comment by bendudson** [comment]
I'm not convinced that the freeboundary code is done in the best way here; it looks like it was added as a test, since it can't be turned on and off for individual variables. 

The motivation was to have operators which use one-sided derivatives at the boundaries, avoiding the need to apply additional boundary conditions for compound operators (derivatives of derivatives).

The whole of this file needs rewriting - see issue #312

**Comment by bendudson** [comment]
This free boundary code has now been removed. The replacement is to use the free boundaries for each variable as needed.
