### ISSUE TITLE
Tokamak-2fluid example

### ISSUE THREAD

**Issue by carlito1720** [boutproject/BOUT-dev#2656]
I'm having  issues running the tokamak-2fluid example. making the file works fine, however when running the command mpirun -np 16 ./2fluid, I get the following error

Initialising PVODE solver
        3d fields = 4, 2d fields = 0 neq=65536, local_N=4096
        Option solver:mudq = 40 (default)
        Option solver:mldq = 40 (default)
        Option solver:mukeep = 0 (default)
        Option solver:mlkeep = 0 (default)
        Option fft:fft_measurement_flag = estimate (default)
Error encountered: Error in generated_fieldops.cxx:599
Fields at different position:`lhs` at CELL_CENTRE, `rhs` at CELL_YLOWapplication called MPI_Abort(comm=0x84000002, 1) - process 4

**Comment by johnomotani** [comment]
Some of the older examples used an early version of staggered grids, and may still need some updating to be compatible with the current implementation if they are not used often. It looks like this is one of them.

You could try setting `StaggerGrids = false` in the `[mesh]` section of the input file, but if the example required staggered grids it might not work... Otherwise `2fluid.cxx` (if that's the C++ file with the PhysicsModel code) needs updating.

**Comment by bendudson** [comment]
Hi @carlito1720! As John says, many of the examples need updating. On top of the usual gradual bit-rot of examples that aren't used often, we've just released a major update (v5) so things that we don't routinely test (like the examples) may be broken. We probably should have a clear-out. 

If you are after 2-fluid simulation models, then there are the STORM and Hermes-3 models: https://github.com/boutproject/STORM https://github.com/bendudson/hermes-3/ that are actively developed and used. They should at least compile.

**Comment by carlito1720** [comment]
Hi. Thank you for your response. I have now tried several versions of BOUT++ ( 5.0, SD1D and hermes-3) and none of them seem to be able to run code that includes a grid. Do you have any suggestions on how to run a code with a grid file.
________________________________

**Comment by bendudson** [comment]
Hi @carlito1720 They can all include a grid file; it's one of the things that BOUT++ handles in the library code. What grid file are you using and error message are you getting? One thing to watch out for is that the path to the grid file in the BOUT.inp file is relative to the working directory, not the directory containing the BOUT.inp file.

**Comment by carlito1720** [comment]
Hi. I have tried different grid file: one I have create with the makegrid code, one included in the BOUT++ git uedge.grd_129131_newpproc.nc<https://console.cloud.google.com/storage/browser/_details/bucket_for_bout/uedge.grd_129131_newpproc.nc?project=sinuous-canto-375712> and uedge.grid, and the one in hermes-3 tokamac.nc.
For all three is get sinilar errors that look like
 Guard cells (x,y,z): 2, 2, 0
        Option ixseps1 = 20 (uedge.grd_129131_newpproc.nc)
        Option ixseps2 = 20 (uedge.grd_129131_newpproc.nc)
        Option jyseps1_1 = 7 (uedge.grd_129131_newpproc.nc)
        Option jyseps1_2 = 32 (uedge.grd_129131_newpproc.nc)
        Option jyseps2_1 = 32 (uedge.grd_129131_newpproc.nc)
        Option jyseps2_2 = 55 (uedge.grd_129131_newpproc.nc)
        Option ny_inner = 32 ()
Finding value for NXPE (ideal = 0.750000)
        Candidate value: 1
         -> Leg region jyseps1_1+1 (8) must be a multiple of MYSUB (64)
Error encountered during initialisation: Could not find a valid value for NXPE. Try a different number of processors.
terminate called after throwing an instance of 'BoutException'
  what():  Could not find a valid value for NXPE. Try a different number of processors.
terminate called after throwing an instance of 'BoutException'

This error is for running $ mpirun -np 8 ../../hermes-3 -d diffusion
I have also tried using a different number of processors as proposed by the error message
________________________________

**Comment by bendudson** [comment]
Thanks @carlito1720. I suspect something strange is going on with your mpirun: The message is saying that each processor has 64 points in Y (MYSUB), but that's the entire grid so it hasn't partitioned at all. I suspect that mpirun has launched 8 jobs, each with one rank, rather than one job with 8 ranks.

At the very top of the BOUT.log.0 file there should be a message like "Processor 0 of 8" if it's really running as an MPI job with 8 ranks. If it says "Processor 0 of 1" then something is wrong with your MPI installation.

**Comment by carlito1720** [comment]
Thank you so much for your help, it is currently running so the problem seems to be solved.
________________________________
