### ISSUE TITLE
next is broken with -DCHECK=3

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#268]
To reproduce:
```
./configure --with-debug && make
```

Fixing field2d.cxx is obvious, but nevertheless, the test_suite fails anyway:
```
./test_suite
[...]
=============================
PASSED: 9 / 15
FAILED: 6 / 15

The following tests failed
   test-laplace
   test-gyro
   test-delp2
   MMS/diffusion
   MMS/wave-1d
   interchange-instability
```

This isn't the first time this is happening - could we add more builds to the travis build-matrix? (Similar to #147 )

**Comment by ZedThree** [comment]
I've got this down to three tests failing: test-delp2, MMS/diffusion and MMS/wave-1d.
These all fail in the same place, `Coordinates::geometry()`, and for the same reason, `MYG = 0`.

This is because `geometry()` calls `DDY`, and the stencils have `bx.jym = -1`. Note that the same problem is in master, but because we use `[]` for indexing, it happily accesses `data[x][-1]`.

As a workaround, we can set `MYG = 1` in these tests, but it doesn't really fix the issue.

---

On the point of more builds in Travis, I think that's a good idea. If we upgrade the Travis VM to trusty, we can build against PETSc as well.

**Comment by dschwoerer** [comment]
The old behavior was, if there haven't been enough guard cells, to default to the last value, therefore implying grad=0 boundary conditions (but low order).
I think the new behavior, of actually failing if there aren't enough points to take the derivative is better.

It seems we have been doing exactly the same, I have just finished fixing the issues ...

**Comment by dschwoerer** [comment]
I guess (except for not allowing MYG=0) this is fixed ...
