### ISSUE TITLE
BOUT installs libfmt.so which conflicts with the fmt package

### ISSUE THREAD

**Issue by yurivict** [boutproject/BOUT-dev#2979]
Could you please use the externally installed fmt?

Version: 5.1.1

**Comment by ZedThree** [comment]
Are you configuring with `-DBOUT_USE_SYSTEM_FMT=on`? That should use the system `fmt`. If you are setting that option and its still installing `libfmt.so`, that's a bug

**Comment by yurivict** [comment]
```-DBOUT_USE_SYSTEM_FMT=off``` installs libfmt.so and its headers.
This is incorrect.
It should not install headers and should only use libfmt.a internally.

**Comment by ZedThree** [comment]
Hmm, this doesn't happen for me.


```
$ cmake . -B build_systemfmt -DBOUT_USE_SYSTEM_FMT=on -DCMAKE_INSTALL_PREFIX=install
...
-- Using external fmt
...
$ cmake --build build_systemfmt --target install
$ tree install
...
├── lib
│   ├── cmake
│   │   └── mpark_variant
│   │       ├── mpark_variant-config.cmake
│   │       ├── mpark_variant-config-version.cmake
│   │       └── mpark_variant-targets.cmake
│   └── python3.12
│       └── site-packages
│           └── boutconfig
│               └── __init__.py
├── lib64
│   ├── cmake
│   │   ├── bout++
│   │   │   ├── bout++Config.cmake
...
│   │   │   └── ResolveCompilerPaths.cmake
│   │   └── PVODE
│   │       ├── PVODEConfig.cmake
│   │       └── PVODEConfig-relwithdebinfo.cmake
│   ├── libbout++.so -> libbout++.so.5.1.0
│   ├── libbout++.so.5.1.0
│   ├── libpvode.so -> libpvode.so.1.0.0
│   ├── libpvode.so.1.0.0
│   ├── libpvpre.so -> libpvpre.so.1.0.0
│   └── libpvpre.so.1.0.0
...
```

My system fmt is 11.0.2. We only set `FMT_INSTALL=on` if using the bundled submodule, and we don't explicitly install any dependencies.

Was this with a clean check out? Or this happening with the release tarball?

**Comment by ZedThree** [comment]
> `-DBOUT_USE_SYSTEM_FMT=off` installs libfmt.so and its headers.

Sorry, misread this, not enough caffeine!

I'm not actually sure I understand the problem. You've building against the bundled `fmt` -- you need to compile models using the same version. We include the fmt headers in some public headers, so they have to be available when compiling physics models.

You can try configuring with `FMT_INSTALL=off`, but that will error because it won't export the fmt CMake config files.

If we did somehow fix that, and only statically linked against fmt, we'd risk running into linktime issues if the system fmt was also linked in.

So I think the only option is to configure with `-DBOUT_USE_SYSTEM_FMT=on` and build against the system fmt.

**Comment by yurivict** [comment]
This makes sense.

Thank you for your explanation.
