### ISSUE TITLE
openmp issue

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#3026]
I would like to build BOUT++ against hypre, but hypre has been build with openmp support.
Should I be able to build BOUT++ without openmp support? Or is this just not reasonable to support?

Right now BOUT++ is providing some openmp functions, if it is compiled without openmp support, but hypre is including openmp headers, if it is compiled with openmp support.

We should probably either support this, or fail during configure. Any thoughts @ZedThree ?

**Comment by ZedThree** [comment]
Are you saying some openmp stuff leaks into BOUT++ via HYPRE headers (if HYPRE is built with openmp)? Or just that we end up needed to link the openmp library? If the first, then if that's deliberate, yes, we probably need to enable openmp. If it's not deliberate, that's a bug in HYPRE.

Off the top of my head, I'm not 100% certain that if a dependency uses openmp whether we're required to _use_ openmp too, but I suspect not. Certainly, we might need to _link_ against openmp, but I'd hope we'd just be able to pull that in transitively, rather than enabling openmp in our build.

**Comment by dschwoerer** [comment]
Yes, it leaks in. How would you determine if it is deliberate?

Linking against openmp would be expected, but I had to enable openmp for BOUT++ to avoid conflicting declarations at compile time. I think we should be fine at link time, as the real openmp library is C - not C++.

**Comment by dschwoerer** [comment]
I noticed only the non-MPI build in fedora is build with openmp.
So after picking the correct hypre this is no further an issue for me.
