### ISSUE TITLE
Backtrace is generated even for caught exceptions

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#326]
If `--enable-debug` is used, then a backtrace is generated for every `BoutException`, even ones that are caught. This involves lots of forking and can slow the code down by several orders of magnitude in certain cases (when an exception is thrown regularly but catching it is fine).

Just removing -DBACKTRACE, then in those cases, the output can be spammed with `Stacktrace not enabled`.

It would be nice if:
1. Backtraces were only enabled at the highest level of checking (probably one higher than the current highest level).
2. Were only generated for uncaught exceptions

**Comment by dschwoerer** [comment]
I don't think that is a good idea, as the backtrace can even be generated if you are running with highest optimization, as in production runs. This allows to debug even cases that only happen after long runs / big systems.

I am not sure about C++ philosophy on throwing, but I guess it is not the same as in python ...

Further I think BoutException should be used for critical stuff, so if you want to do loads of throwing and catching, and are unwilling to just use ifs, why not write your own exception?

About being spammed with `Stacktrace not enabled` - thats a bug as it shouldn't printed, but be added to the buffer.

If you don't agree with any of my options, that I think only option 2 would be in my opinion be acceptable.

PS: What are you doing that generates that many exceptions?
Are you just looking at test cases that are slow, due to e.g. initialisation overhead, or really at production cases.

**Comment by d7919** [comment]
Could we just add an `--enable-backtrace` option to configure? That way the user has complete control (through the usual interface) of if they include the backtrace or not?

**Comment by bendudson** [comment]
I vote for an --enable-backtrace configure option

**Comment by ZedThree** [comment]
Fixed in #781
