### ISSUE TITLE
Some options in certain sections cannot be changed from the command

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#36]
non-standard sections cannot be changed from the command line. E.g. having a section in BOUT.inp whose parameters/options are read in physics_init cannot be altered from the commandline using the -section:option=X syntax

**Comment by bendudson** [comment]
This should work, as there's no special treatment for any sections.

You don't need a "-" at the start, so setting "nx" in section mesh is " mesh:nx=X" (no leading dash). Similarly for an option read in physics_init.

**Comment by JensMadsen** [comment]
Sorry :-D It is actualy how it is written in the manual. I got confused because -nxpe= 16 works etc

**Comment by bendudson** [comment]
This probably should be a bug of some kind, since the handling of leading "-" should be consistent. In src/sys/optionsreader.cxx lines 55 and 80 strip out the dash if given:

bool startdash = buffer[0] == '-';
...
if (startdash) buffer = buffer.substr(1);

but then for some reason the options are only split into sections if there's no dash:

Line 97: 
    if(!startdash) {
        // Only split into sections if no dash at start
        size_t scorepos;
       ...

Is there a good reason to do this? The only reason I can think of is that the section separator used to be "_" (underscore), so if you wanted an option with an underscore in the name then there needed to be a way to stop treating it as a section delimiter. Now the delimiter is ":" (colon), so the only reason to keep this "feature" is if anyone wants to have option names with ":" in them.

**Comment by bendudson** [comment]
Fixed in commit 952ac9adc88e
