### ISSUE TITLE
Calculating Christoffel symbols crashes if MYG=0

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#376]
Calculating the Christoffel symbols in [`Coordinates::geometry`][1] uses `DDY` which will throw an out-of-bounds exception if `MYG=0`.

We either need to require `MYG != 0`, fix DDY somehow, or change how the Christoffel symbols are calculated.

[1]: https://github.com/boutproject/BOUT-dev/blob/next/src/mesh/coordinates.cxx#L232

**Comment by bendudson** [comment]
If MYG=0 then the grid is essentially 2D (X,Y) since no coupling in Y is
used. In that case could Christoffel symbols be calculated by setting DDY
terms to zero?

I would be in favour of thinking more carefully about the Christoffel
symbols: The few times I've actually tried using them in a simulation,
they've been too noisy to use. Instead it was better to re-write the
operator in a way which did not use the Christoffel symbols (e.g full
divergence form)

**Comment by ZedThree** [comment]
I think there's a few other surrounding issues that could probably be wrapped up into a rethink of the metrics (e.g. #338, #232, #274).

**Comment by loeiten** [comment]
I agree with @bendudson. Big care should be taken as the Christoffel symbol can give rise to high noise in the system due to the introduction of numerical errors in these terms.

Also, in order for `Vector3D DDZ` to work, extra Christoffel symbols needs to be taken into account (see #123, #316)

**Comment by bendudson** [comment]
This bug is now fixed by PR #485, though the underlying issue of how Christoffel symbols are used remains.
