### ISSUE TITLE
How to pass BoutReal

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#402]
There are different ways to pass a BoutReal to a function `f`
```
f(const BoutReal a);
f(BoutReal a);
f(const BoutReal &a);
```
They are all the same from the point of the user (I am not sure about the reference in terms of performance).
However, in terms of function signatures, they aren't.

All are used:
Option 1:
https://github.com/boutproject/BOUT-dev/blob/v4.0.0-RC/include/field3d.hxx#L405
Option 2:
https://github.com/boutproject/BOUT-dev/blob/v4.0.0-RC/include/field3d.hxx#L512
Option 3:
https://github.com/boutproject/BOUT-dev/blob/v4.0.0-RC/include/field3d.hxx#L410

Which way should be preferred?
Or did I miss something, and there is a good reason to have the differences?

**Comment by bendudson** [comment]
Sorry, this is what happens when a code is around for a while without any style guide (and a developer who can't make up their mind).

The consensus here:
http://stackoverflow.com/questions/270408/is-it-better-in-c-to-pass-by-value-or-pass-by-constant-reference

 seems to be that it doesn't matter very much, but that option 2 (pass by value) is preferred for small things like BoutReal (double).

I think option 1 is the same as option 2 (const redundant)


-------- Original Message --------

**Comment by dschwoerer** [comment]
You are right, I didn't know that const is an implementation detail:
http://stackoverflow.com/a/3969745

**Comment by dschwoerer** [comment]
Closed with #409
