### ISSUE TITLE
Deprecate functions

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#405]
I think deprecated functions shouldn't be used in the library.

The point of deprecating them, instead of removing them, should be to give the users time to adapt there code, without breaking it.

I think this would be a point to add to style guide.

**Comment by ZedThree** [comment]
#415 tidies up the remaining uses of `bout_error`. I'd missed this as my compiler wasn't hitting them. It also removes uses of `FieldData::getData/setData`.

`Mesh::getXcomm()` is a bit tricky to deal with, but does need to be sorted.

Are there any other deprecated functions that I've missed?

> The point of deprecating them, instead of removing them, should be to give the users time to adapt there code, without breaking it.

Indeed, and I believe this is how we're using them. The development of BOUT++ is very distributed, so they also serve as a reminder/notice to other developers that they should use something different.

**Comment by bendudson** [comment]
I think there is a large overlap between the "library" developers and the users. Most developers (myself included) don't know how all parts of the code work, so when deprecating functions it's used as a reminder of where code needs updating.

The getXcomm() function was deprecated as a way of finding where it would need to be replaced. As @ZedThree says, there are places where replacing it would be more difficult than initially thought, so a better design is probably needed. The deprecation is there as a reminder... perhaps issues would be better.

getXcomm() is deprecated because it assumes that there is only one communicator in X, i.e. there are no branch cuts in X. This is quite restrictive, so the options are:
1) Generalise to allow branch cuts. getXcomm(int xindex) was an attempt at this, but probably not the right way. Some way to group ranges of indices (or DataIterator?) would be better
2) Give up, and just make it an assumption that there are no branch cuts in X.

**Comment by dschwoerer** [comment]
I perfectly understand that current design isn't perfect in many places and should be improved. And deprecating function s is certainly the way to go, instead of suddenly changing the interface.

As no one knows what the others are doing / working on / what they are using what for, it is certainly not possible to change all of that. But if you push changes to a branch / open a PR to deprecate stuff, I think at least all usages of the deprecated function should be changed. If that is not possible, as in the `getXcomm()`, than the new design is probably not sustainable.

For such challenging changes, I think opening an issue is a good place to discuss it first.

Why I dislike to do it the way it is currently done, by deprecating the old interface before there is a new one, that there are so many deprecated warning, I will most likely miss the ones that are in my code, and that I need to fix.

I already looked at the `getXcomm()` and was thinking about adding a dummy argument - certainly not the way to go, but it would have quieted the warning - so I can see the warnings in my parts ...

**Comment by dschwoerer** [comment]
@ZedThree instead of just looking for the compiler output, `grep` is really handy :)
This way you can also make sure there are none left in the examples folder (without actually needing to compile them all)
