### ISSUE TITLE
Restart should be moved from the solvers

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#439]
As far as I can see, the solvers are reading the restart files upon restart.
This means that any modification to the fields in `init` will be overwritten.
This should maybe be changed as

1. It is hard to debug, and the only workaround seems to be an `if` statement in the `RHS` function which checks whether the current simulations is a restart or not.
2. Intuitively one would think that the solvers task is to solve, and not read restart files.

**Comment by bendudson** [comment]
Correct, this is currently done during solver initialisation, after the evolving fields have been added in init
https://github.com/boutproject/BOUT-dev/blob/v4.0.0-RC/src/solver/solver.cxx#L643

Would it be an improvement to have solver read the restart file when SOLVE_FOR   (solver->add) is called, rather than when the solver is initialised? The init routine could therefore modify it if needed. This would be consistent with starting from scratch, where the fields are initialised when SOLVE_FOR is called.

Ultimately I agree, it probably would be better to separate restart files and solvers. This would however leave it up to the user to properly handle saving and restoring restart files.

**Comment by JensMadsen** [comment]
> Would it be an improvement to have solver read the restart file when SOLVE_FOR (solver->add) is called, rather than when the solver is initialised? The init routine could therefore modify it if needed. This would be consistent with starting from scratch, where the fields are initialised when SOLVE_FOR is called.

That would be an improvement :-D Since solver::restaring is protected you have to make your own flag if you want to modify fields read from restart files and you have to make the modifications in the rhs method.

**Comment by loeiten** [comment]
Eventually, a `post_init` function could check for restart, and do the necessary steps.

**Comment by bendudson** [comment]
With the "new" PhysicsModel class, the restart handling (post_init function) could be a virtual function which can have a sensible default, but overridden by the user if they want to do something unusual.

**Comment by ZedThree** [comment]
We could just move most of the relevant bits out of `Solver::init` into `PhysicsModel::post_init` so it remains completely backwards compatible. Feature for 4.1?

**Comment by bendudson** [comment]
Sounds like a good solution. I second that for v4.1
