### ISSUE TITLE
zShift for Python

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#46]
To shift back into orthogonal (psi, zeta) coordinates, need a Python routine to perform FFTs and apply phase shift.

**Comment by johnomotani** [comment]
Could this also help 3D visualisation? If we pre-process the data back to an orthogonal grid, it might be much easier to set up any 3D visualisation program to plot things without needing to do lots of fancy interpolation, etc.

If this is a common thing to want, it might also be helpful to have an option in BOUT++ to output data in orthogonal coordinates instead of/as well as in field-aligned? I guess it would not be hard to implement, since all the shifting routines exist already.

**Comment by d7919** [comment]
I think this is possibly invalid now (or at least needs updating) -- the fields can now be written in either shifted or unshifted coordinates.

**Comment by dschwoerer** [comment]
With #641 it should be easy to implement - I just wasn't sure what function was required/requested.

**Comment by johnomotani** [comment]
This feature is now provided in `xBOUT` https://github.com/boutproject/xBOUT/pull/105.
