### ISSUE TITLE
BOUT++ visibility

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#478]
[This](https://github.com/search?utf8=%E2%9C%93&q=BOUT%2B%2B) needs improvement.

Should we [rename](https://help.github.com/articles/renaming-a-repository/) BOUT-dev to BOUT++?

**Comment by bshanahan** [comment]
I support this. Better web presence (in general, not just on github) would greatly benefit us.

**Comment by d7919** [comment]
Would it be worth looking at something like [this](https://help.github.com/articles/search-engine-optimization-for-github-pages/) as well?

**Comment by ZedThree** [comment]
Absolutely. This next week I'll be getting the new website sorted, and I'll be looking into improving our google ranking if possible.

I'm definitely in favour of renaming the repo. I was going to say I would be worried about people having broken links, but it turns out [Github will redirect requests][1] to the new name.

[1]: https://github.com/blog/1508-repository-redirects-are-here

**Comment by ZedThree** [comment]
Github, rather unfortunately, changes `+` into `-`, so `BOUT++` would be transformed into `BOUT--`, which gives a slightly different impression...

**Comment by dschwoerer** [comment]
This is so annoying.
Searching for BOUT++ now shows this repository in second place 👍 

Domains cannot contain `+` ether ...
so bout++.org isnt possible, but [boutplusplus.org](https://secure.domain.com/register/domains/?dom_lookup=boutplusplus) or [boutpp.org](https://secure.domain.com/register/domains/?dom_lookup=boutpp) seems possible ...
