### ISSUE TITLE
Differing nrhs with changing processor count

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#48]
I've noticed that the nrhs count can vary a bit when running on different processor counts. This was with a case using cvode and running on either 4 or 8 cores. The count was identical for most outputs but some are somewhat different (49 vs 74). 

The rms fields look near identical so this may not be too concerning, but it would probably be good to understand.

**Comment by johnomotani** [comment]
"Varying the number of processors will alter the output, only because of roundoff-level differences in various vector operations" (https://computation.llnl.gov/casc/sundials/documentation/cv_examples.pdf). I guess (or rather hope) that you are just above or below some threshold for timestep adjustment (presumably the difference in number of iterations is from just one extra internal timestep?), varying depending on round-off errors or some such. Does changing the tolerances slightly affect things?

**Comment by d7919** [comment]
Changing the tolerances by 10% leads to a change in nrhs for repeat runs on the same number of cores. I guess this suggests I'm accuracy limited so small tweaks in round off could conceivably lead to changes in nrhs.

I guess at some point the time step will become physics limited and then nrhs should be independent of nproc. I'll have a look.

**Comment by d7919** [comment]
Increasing my atol from 1.0e-12 up to 1.0e-3 I find that running on 2 and 4 cores I get the same nrhs, however the majority of the first 14 (out of 35) of my outputs have nrhs=1, which may impact on this comparison (usually the differences in nrhs didn't occur until towards the end of my test).

Dropping atol to 1.0e-4 or lower, I see a discrepancy between the nrhs for 2 and 4 core runs (rtol doesn't seem to impact things).

**Comment by johnomotani** [comment]
I guess if you are limited by atol at 10e-14 then differences in round-off error are reasonably likely to have an effect (chances of being within roundoff of the tolerance at some point in 35 tries is I guess about (1-10e-16/10e-14)^35 ~ 0.7 and will increase to near unity if you have many internal timesteps per output). So sounds to me as though it is just differing round-off rather than any bug?

**Comment by d7919** [comment]
Yes I agree it's unlikely to be a bug and is most likely some round off related issue (though it comes in at fairly loose tolerances, which surprises me slightly). 

I just thought I should flag this as:
*Perhaps this is something that can/should be documented (prevent similar issues being raised).
*I hoped someone may have a better understanding (which you've provided!)

Thanks
