### ISSUE TITLE
y initial conditions always at CELL_YLOW

### ISSUE THREAD

**Issue by JosephThomasParker** [boutproject/BOUT-dev#484]
Initial conditions for y seem to be evaluated at CELL_YLOW, even when a variable is located at CELL_CENTER.

I modified the test-staggered example ![here](https://github.com/JosephThomasParker/BOUT-dev/tree/staggered-bc/examples/test-staggered).  In this is test, density is located at the cell centre and has the initial condition `1+0.01*cos(y)`.  Velocity is located at YLOW and has ICs `1+0.01*sin(y)`.  

To plot the ICs actually used, do
`./runtest`
`cd test`
`python plot_staggered_ic.py`

Velocity (green) is correct, but the density (blue) should be offset by half a grid spacing, so that it would be 1.01 at the boundary and 1+0.01*cos(dy/2) at the first grid point. 

![figure_1](https://cloud.githubusercontent.com/assets/15211161/23663039/5145537c-0349-11e7-96ee-fd427acf1af8.png)

**Comment by bendudson** [comment]
Ah, it might need to have mesh:symmetricGlobalY = true set, in order to define the Y coordinate properly. This is what is done in the MMS tests:
https://github.com/boutproject/BOUT-dev/blob/master/examples/MMS/wave-1d-y/data/BOUT.inp#L32

The default is currently false, since changing would "break" some tests
https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/impls/bout/boutmesh.cxx#L60

This modifies how the global Y index is calculated here:
https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/impls/bout/boutmesh.cxx#L2256

then if the cell location is YLOW the index is interpolated to the cell boundary:
https://github.com/boutproject/BOUT-dev/blob/master/src/field/field_factory.cxx#L133

whilst if it's CENTRE then the index at cell centre is used:
https://github.com/boutproject/BOUT-dev/blob/master/src/field/field_factory.cxx#L144

**Comment by JosephThomasParker** [comment]
Thanks Ben!  With `mesh:symmetricGlobalY = true` it works as expected (though the lower BC for the staggered grid must be put in manually, as is the point of the example).

![figure_2](https://cloud.githubusercontent.com/assets/15211161/23666471/06c4e11e-0353-11e7-97a5-861a5f16f09b.png)

**Comment by bendudson** [comment]
We probably shouldn't depend on a magic "make this work properly now" switch. 
Should changing symmetricGlobalY to true by default be a 4.1 change? It will change things, but I think the default should be changed to do the right thing

**Comment by bendudson** [comment]
I thought the boundaries should now be applied properly for staggered variables... but perhaps not

**Comment by JosephThomasParker** [comment]
Ok, I extended the test to loop through `symmetricGlobalY` true/false and `StaggerGrids` true/false (and also periodic/nonperiodic, but that makes no difference).  Now `runtest` ![here](https://github.com/JosephThomasParker/BOUT-dev/tree/staggered-bc/examples/test-staggered) produces four figures:

**StaggerGrids false, symmetricGlobalY false:**
![staggergrids_false_symmetricglobaly_false](https://cloud.githubusercontent.com/assets/15211161/23674201/fe0de268-036c-11e7-9d67-e1a250d06969.png)

WRONG: Both should be evaluated at the cell centre, but both are evaluated at ylow.

**StaggerGrids false, symmetricGlobalY true:**
![staggergrids_false_symmetricglobaly_true](https://cloud.githubusercontent.com/assets/15211161/23674203/fe10c41a-036c-11e7-9f07-2eedaebe8287.png)

Correct: both are at the cell centre.

**StaggerGrids true, symmetricGlobalY false:**
![staggergrids_true_symmetricglobaly_false](https://cloud.githubusercontent.com/assets/15211161/23674202/fe10253c-036c-11e7-9222-cb460199134a.png)

WRONG: Blue is at ylow when it should be at centre.  Green is at cell centre when it should be at ylow, and is also shifted right one grid point relative to the case above.

**StaggerGrids true, symmetricGlobalY true:**
![staggergrids_true_symmetricglobaly_true](https://cloud.githubusercontent.com/assets/15211161/23674204/fe334fc6-036c-11e7-98df-19bb0682a6d5.png)

Correct: blue is cell centre, green is cell ylow (with the zeroth point not set).

**Comment by dschwoerer** [comment]
Fixed by #561
