### ISSUE TITLE
Ballooning initial profiles

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#50]
From initialprofiles.cxx:110 it looks like the ballooning flag only impacts initial conditions set using the old/backwards-compatible approach. Is this correct and the intended behaviour?

**Comment by bendudson** [comment]
This was done originally because I couldn't see a nice way to include this
ballooning flag in the new FieldFactory expressions.

The quick fix could be to make it work like the old method, so evaluate the
expressions at (y+n2pi, z+qn2pi). This would probably be less surprising.

A nicer way night be to have a "ballooning" function in the expressions.
Not sure how this should get the q from the mesh though.

**Comment by bendudson** [comment]
A function ballooning() has now been added to FieldFactory, allowing ballooning transforms in analytic expressions
