### ISSUE TITLE
Merge policy: master vs next

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#543]
#522 and #541 are both fixed in next, but not in master.

Should we merge next more often to master, or is anybody willing to cherry-pick al bug fixes from next to master?
Advertising master as stable, if it is less stable than next might not be good for winning new users ...

In regards to this, I was wondering to what extend we want to support 4.0 after 4.1 is released?
I think there is no point in doing so, as this binds additional time, and there are better ways to spend it ...

**Comment by bendudson** [comment]
I think bug fixes should be cherry picked from next to master, though remembering to do this is a different matter. The grey area is around fixes which require significant changes.

I would be in favour of only supporting the latest release; we do not have the time/resources/energy to have long term support. Users should nearly always be using the latest next anyway.

**Comment by dschwoerer** [comment]
If we want users to use next, why do we not tell them to?
The master branch is the default by git but I am not sure to what extend we want it to be used. Would it make sense to rename master to stable and next to master?

Further, would it make sense to often merge next into master? This way, we don't need to cherry pick. Master would benefit from all changes, if we wait a few days after the latest merge, it should be somewhat tested, and therefore the chances of having a bad merge in master should be lower than in next.

Finally, as we are referring mostly to releases (and there are known bugs in them) should we release master on a monthly basis, after running an extended set of tests?
We have a somewhat powerful server, that could pull and build monthly releases, and run a more extensive test suite.

**Comment by bendudson** [comment]
I think the current policy makes sense, which is:
* master is what new users and people who want to try out BOUT++ and get started with should get.
* If someone is going to be doing development, or trying to use more advanced/experimental features, then they probably should be using next.
* we support each release with bugfixes as long as it is master

I don't think a fixed release schedule would be useful personally, but I agree an extended set of tests would be good. Because most people using BOUT++ just want to get on with their research, they tend to update very infrequently e.g. PhD students download at the start of their PhD and never update. Not recommended, but does happen quite often. I think it can therefore take quite a long time (weeks to months) for issues to be found and solved. If someone is going to be a user who does not really know how to use git, then I'd rather they got a copy of the stable branch than the next branch. Users who are more likely to update regularly can switch their branch to next.

**Comment by dschwoerer** [comment]
Ok, makes more sense now 👍
