### ISSUE TITLE
Having two or more output intervals

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#56]
Hi 

I would like to to the following: 

1) output the fields (particle density, etc) every e.g. 100 timeunits. (timestep = 100 in BOUT.inp)
2) output the total energy (or another scalar, could be synthetic probe data etc.) every 10 timeunit

I do not want the  functionality in the timestepmonitor (see user manual p 88).

**Comment by bendudson** [comment]
This would probably need two different output files for now, since NetCDF only allows one expanding time dimension. 

I think the most flexible way to do this is to have a sorted queue of output times and associated monitors, which can be an arbitrary point in time. A monitor is added to the solver like an alarm clock, to be called at a particular simulation time:

solver->addMonitor( MyMonitor, simtime + 100 );
solver->addMonitor( MySecondMonitor, simtime + 10);

These monitors go in a queue. The solver then finds when the next monitor should be called, runs to that time, and calls the monitor. When the monitor is called, it then adds itself to the solver to be called again.

This would allow multiple monitors with different timesteps, and would also allow monitors to adjust their output timesteps.

**Comment by JensMadsen** [comment]
having more than one output file is an advantage in my opinion. Should speed up reading the files.

Your proposed design looks good.

Jens Madsen
PPFE, DTU Physics
Denmark
________________________________

**Comment by dschwoerer** [comment]
I guess this hasn't been implemented?

**Comment by dschwoerer** [comment]
I am not sure this is the best way:
* The monitor would need to be re-added every time they are called - most monitors would probably be used more than once.
* If I have one timer which should be called every 1 time unit, and one every 10, the solver would need to stop at 10 twice, cause 10 != 1*10 (using floats)
* Every solver would have to implement the whole logic for finding the next monitor

I was wondering, whether it would not be sufficient to allow sub/super sampling.
I can safe the density of a single point every 1 time unit, the other output monitors are only called every 10th time.
The disadvantage would obvious be, I cannot call a Monitor after pi time units (unless every output is a multiple of pi)

If the faster timers are added in the physics_init() code, it might not even be required to change the code of any solver implementation (I hope) ...

**Comment by dschwoerer** [comment]
I have a draft here: https://github.com/dschwoerer/BOUT-dev/tree/multi_timestep_monitor
`Monitor` is now its own class, and 
```
Monitor m=new Monitor;
m->timestep=1;
solver ->add(m);
``` 
Will call the monitor every time unit, even if the timestep for the output is eg. 10.

It is currently still lacking documentation.

I am not sure the current interface is good, but I would prefer using classes instead of function pointers ...

I needed to change the pvode code as it resetted the rhs evaluation counter (other solver do as well ...)

**Comment by bendudson** [comment]
I think I agree that a fixed (integer) multiplier is the simplest way to do this. The solver timestep can be specified, setting the highest frequency output. All outputs are at multiples of that underlying time period. 

Your solution using classes is certainly much nicer than function pointers. Would passing the multiplier to the constructor be better, rather than modifying a data member? That way it could be prevented from being modified at a later time with strange consequences...

    Monitor *m = new Monitor(10);

or to be more consistent with the other parts of the code:

    Monitor *m = Monitor::create(10);

**Comment by dschwoerer** [comment]
I guess passing the output time to the constructor is a cleaner way ...

I am not sure where in the code the create is used - what is wrong with using constructors?

Right now the monitors are called at the end of an iteration. With the exception of the first iteration, where it is also called in the beginning - should in this case the iteration number not rather be -1, as it is the end of the one before the zeros?
My current version does not call the output monitor in the beginning due to this issue.
Another option would be to to pass an increased iteration number, so that the last call would be if iter == nout?\
However that could brake code, depending on the current implementation ...

**Comment by JosephThomasParker** [comment]
Here's a simple implementation for writing out at integer multiples of the timestep:
https://github.com/JosephThomasParker/BOUT-dev/tree/time_subsampling
There's a test case in `examples/blob2d-time-subsamping`, but all you need to write out a variable at every `n`th step is set `subsample=n` in a variable's section of `BOUT.inp`.  The changes are purely in the BOUT library, so this will work with any physics module with no changes required.

The data gets written to the first `1/n` values of the netcdf file, so when you `collect` it with python, the data is in `phi[:len(phi[:,0,0,0])/n+1,:,:,:]`, but the relevant time points are `t[::n]`.  

It turns out this was easier to implement without monitor functions.  When BOUT writes, it calls `Datafile::write`, which loops through structs which correspond to the variables to be written, and writes the variables to the single netcdf file.  In this implementation, we just add a `subsample` integer into each variable's struct, and don't write to file unless the current iteration is a multiple of `subsample`.    

[test-subsample.pdf](https://github.com/boutproject/BOUT-dev/files/711149/test-subsample.pdf)

**Comment by dschwoerer** [comment]
Not having tested that, but doesn't that create a huge file with non-initialized values?
If I want to sub sample all 3D fields, and have only a few 1D points at high frequency, that creates a huge (nearly empty) datafile?

I can see that being able to have multiple output monitors by changing BOUT.inp would be handy (I think it would also be possible to that with my implementation ... )

**Comment by JosephThomasParker** [comment]
I don't think it does - at least I found that halving the number of samples roughly halves the file size, provided what we are sampling is the largest array.  Either way, that's unavoidable if we choose to have a single netcdf file. 

I did _intend_ to use your implementation... :-) and I'd certainly agree that that's the way to go about it if we introduce more than one output file.

**Comment by dschwoerer** [comment]
I think having more than one output file is easier, as it would for example allow to have the correct time matching to the data.

Did you had any issues using mine? Are there any bugs or usability obstacles?

**Comment by JosephThomasParker** [comment]
Sure - I don't have an opinion either way one single vs. many output files, but it seems like a decision for the community (or the benign-dictator-for-life).   (Also, I suppose I could work around the time/data mismatch by, for example, writing the fill value explicitly rather than skipping the write.)

I didn't have any problems with your implementation (besides my own learning curve...) - it's just if all the writes are done in one file, you only need the one monitor that is already in bout++.cxx

**Comment by ZedThree** [comment]
One more option is use multiple time dimensions in a single output file. There used to be a restriction of a single unlimited dimension in NetCDF3, but this was lifted in NetCDF4 when they switched to using HDF5 as the backing format. This may require a change to the collect routines, though it could be done without breaking backwards-compatibility.

NetCDF files also support groups, as in HDF5, so we could organise variables into different groups according to their sampling frequency. This may very well break backwards-compatibility.

My personal preference would be to keep things in a single file where possible.

**Comment by bendudson** [comment]
Fixed in 4.1 by PR #346
