### ISSUE TITLE
How to get valid mesh?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#593]
I am trying to get a mesh.
I tried to expose the MeshFactory (put it in the `include` folder) - but the mesh created by this does not have a valid number of grid points.
Am I missing something?
The mesh is reading from the mesh section, but it does not read `nx` etc.

**Comment by bendudson** [comment]
The mesh initialisation currently consists of three steps:

    mesh = Mesh::create();  ///< Create the mesh
    mesh->load();           ///< Load from sources. Required for Field initialisation
    mesh->setParallelTransform(); ///< Set the parallel transform from options

https://github.com/boutproject/BOUT-dev/blob/master/src/bout%2B%2B.cxx#L272

This is/was because fields use the global mesh, and mesh initialisation loads fields. First the global mesh pointer is set, then the mesh is loaded. Yes I know this is not nice... sorry.

**Comment by dschwoerer** [comment]
Thanks, works like a charm 👍
