### ISSUE TITLE
BOUT.settings contains datadir

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#602]
`BOUT.settings` includes `datadir` and if it is used as input file from another location, this will cause the `datadir` to be overwritten. Instead of the (correct) version from the command line, the (wrong) version from the datafile is used.

Expected behaviour:
* ignore `datadir` from `BOUT.inp` (the input file)
(alternatively: don't write `datadir`)

**Comment by dschwoerer** [comment]
Update: A workaround is to specify the `datadir` as both `-d fu` and `datadir=fu`

**Comment by d7919** [comment]
Is this because `datadir` is a "special" option that has its own flag as well as a name? Usually the command line option should take precedence.

I was going to propose that we put the value passed to `-d` into the option tree as `datadir` such that we don't go to the file to find it, but it turns out we do that [already](https://github.com/boutproject/BOUT-dev/blob/master/src/bout%2B%2B.cxx#L173)! 

When you say the `datadir` is overwritten, do you mean the contents of the directory is overwritten, or the value of `datadir` written into the settings file is overwritten?

I'm not sure about the handling of the `-d` flag in [options](https://github.com/boutproject/BOUT-dev/blob/master/src/sys/optionsreader.cxx#L40)

**Comment by dschwoerer** [comment]
1. Yes, I assume that is why the option parser ignores the pre set value.

2. Maybe we could add `-d bla` by the initial parser as `datadir=bla` to the options?

3. I mean the value of `datadir` in the parser is overwritten. Actually, this makes sure that in my case nothing gets written, as the second invocation of the option writer fails.

4. I think `options` knows nothing about the `-? bla` flags.

**Comment by ZedThree** [comment]
Fixed in #1382
