### ISSUE TITLE
Arithmetic in input file when variable is specified on command line

### ISSUE THREAD

**Issue by lukeeasy** [boutproject/BOUT-dev#62]
I've found that if you perform arithmetic in the input file using other variables, and then specify the variable used for the calculation on the command line, then the value given in the input file is used.  

For example, I quite often do something like this:
```
[mesh]
Lx = 100
nx = 32
dx = Lx/dx
```

But if I were to specify Lx on the command line as 200:
```
mpirun -np 1 example mesh:Lx=200
```

dx is still calculated as 100/32

**Comment by bendudson** [comment]
This should work, because the command-line arguments are parsed and put
into the options before the mesh is created.

In bout++.cxx

line 247: reader->parseCommandLine(options, argc, argv);

inserts options from the command line into the options tree, overwriting
any from BOUT.inp (which is read on line 244).

The mesh is then created on line 295 and 296.

When the mesh reads dx, the value of Lx used will be printed in the log
file. This should specify where the source of the setting was (default,
BOUT.inp, or command line). What value is printed?

**Comment by lukeeasy** [comment]
My bad, I think it does work after all.  Sorry!
