### ISSUE TITLE
Options:set()

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#620]
I have been trying to use the set feature of the options class.

I have a mesh, and try to set the number of z points.
`BOUT.inp` looks like this:
```
[meshz]
nz=n
n=4
```
If I use:
```
    boutcore.setOption("meshz:n","%d"%nz)
    boutcore.setOption("meshz:nz","n")
```
The first mesh created from this option is created with correct settings, however if I call this section again, and create a new mesh, it keeps the first setting.

What works, is setting directly `meshz:nz`:
```
    boutcore.setOption("meshz:nz","%d"%nz)
```

Note: I set all options as string.
While I have a work around, it would be great if I could write MMS code that was less depending on the direction, and I could just set n. Further, I also need to update `dz` by hand ...

**Comment by bendudson** [comment]
I think this is due to the caching: The assumption was that options are set at the start, and would not be modified during the simulation. The aim was to reduce the need for expensive repeated parsing of expressions.

Grid calls options: https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/data/gridfromoptions.cxx#L18

Options calls FieldFactory: https://github.com/boutproject/BOUT-dev/blob/master/src/sys/options.cxx#L79

FieldFactory checks the cache: https://github.com/boutproject/BOUT-dev/blob/master/src/field/field_factory.cxx#L341

Modifying options doesn't play well with this caching, or with the recording of settings in BOUT.settings. 

Would a good solution be to make options write-once? Attempts to set an option which have already been set would result in an error. This would however cause problems for the initial reading of command-line arguments, which overrides settings from BOUT.inp.

I propose a locking mechanism for Options:

void Options::lock()    // Locks options: new settings can be added, but never overwritten. Once locked it can't be unlocked
bool Options::isLocked()   // Checks if the options are locked

FieldFactory could then check if the options are locked. If they are then caching is safe, but if they are not then caching is disabled.

**Comment by bendudson** [comment]
Where could the lock() function be called to allow your code to avoid calling it? I was thinking it could go after reading command-line arguments in BoutInitialize, but then it would always be called. Perhaps in the default main() function somewhere before solve()

https://github.com/boutproject/BOUT-dev/blob/master/include/bout/physicsmodel.hxx#L265

That way the physics model could still do funky things with the options in the initialisation, though not in the rhs (which I think is probably a good thing on balance). Presumably the code you're using also doesn't use this main() function, so could call Options::lock() optionally as a (small) optimisation.

Alternatively we could just disable caching... premature optimisation and all that

**Comment by dschwoerer** [comment]
Another option, with which I would be happy, would be to extend the interface to force a cleaning of the cache.

I am not sure whether any codes rely on parsing being fast. The fastest option would be to save anything in the physics-module that is needed again ...

I had a look at the examples, and most examples don't have a lot of cache uses.
`MMS/wave-1d-y` has around 96% cache hits. All other cases have less then 50% cache use.

If used [this branch](https://github.com/dschwoerer/BOUT-dev/tree/check_options_cache) to test the efficency ...

One thing beyond performance: if the options is cached, it will not be printed again ...
If the output is discarded, the difference for the `MMS/wave-1d-y` (where the source terms are not cached) is 0.735 s vs 0.831 s, and if output is not redirected, this increases further to 1.029 s.

So, if the cache is used to generate time dependent expressions, it is indeed very useful.
However, cleaning the whole cache after every call of set seems imho reasonable, but I wouldn't mind if I need to call this by hand ...
