### ISSUE TITLE
Arithmetic support for all variables in BOUT.inp

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#72]
It could be nice to support arithmetics for all variables, as far as I can see, if
```
[foo]
bar = 1.0 + 2.0

[baz]
qux = foo:bar
```
is specified in the input file, ```Options *fooOp = options->getSection("foo")->get("bar", bar, 3);``` will return ```1``` to ```bar```, and  ```Options *bazOp = options->getSection("baz")->get("qux", qux, 3);``` will return ```0``` to ```qux```.

**Comment by bendudson** [comment]
I'm pretty sure Options *meshOp = options->getSection("mesh")->get("bar",
bar, 3); wouldn't work in the example given; options would still try to
parse "1.0 + 2.0" as an int, probably returning 1. There's nothing special
about the "mesh" section, and Options has no hard-wired section names for
special handling.

Mesh options can use expressions, and things involving "pi" etc. because
Mesh (using GridFromOptions) reads the options as strings, then passes them
through the expression parser to convert to numbers. When you read a
quantity using mesh->get (or the GRID_LOAD wrapper around it) FieldFactory
is used to convert the strings to values, and do the lookup of other
variables.

The closest at the moment would be:

BoutReal value = FieldFactory::get()->parse("foo:bar",
Options::getRoot())->generate(0,0,0,0);

This first gets a FieldFactory ( FieldFactory::get() ), then calls the
"parse" function which takes a string to resolve ("foo:bar") and a section
to look in, here given as the root section. The parse function returns a
FieldGenerator*, so to turn this into a value you need to generate with
given (x,y,z,t) values.

One way to do this might be to have all calls to Options::get(BoutReal...)
use FieldFactory rather than the stringstream >> operator (see e.g.
options.cxx line 103). These would have to choose values for (x,y,z,t),
probably (0,0,0,0) as above.

For integers things are a little more tricky. At the moment the
FieldFactory / ExpressionParser code treats all values as BoutReals. I
suppose we could generate values as BoutReals then round to the nearest
integer. Note that since this is in Options, it would affect everything
from reading nx,ny onwards.

Votes for/against implementing this?

**Comment by loeiten** [comment]
Thanks.

Yes, my example didn't work as you said, so I changed the original post just before you replied (sorry about that).

My question is rather about arithmetics for normal variables, so that if we in ```BOUT.inp``` had
```
[foo]
bar = 2.0*pi
```
and in our code wrote ```Options *fooOp = options->getSection("foo")->get("bar", bar, 10.0);``` it would return ```3.14...```.

If I understand you correctly,
```
BoutReal value = FieldFactory::get()->parse("foo:bar", Options::getRoot())->generate(0,0,0,0);
```
will work for this purpose.

As for the voting. I have not looked too much into the Option class, so I do not know if what you suggest is very time consuming, but if it is not, it strikes me as a good idea.

**Comment by bendudson** [comment]
It wouldn't be very time consuming to implement I don't think, probably a
matter of adding a line similar to this:

BoutReal value = FieldFactory::get()->parse("foo:bar",
Options::getRoot())->generate(0,0,0,0);


which should do what you need I think. Some checking would need to be
done that FieldFactory didn't depend on Mesh, #
for example, since Mesh needs to use these Options routines to initialise.
