### ISSUE TITLE
Building with c++11

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#89]
Would it be possible to add ```-std=c++0x``` as a flag in ```configure.ac```?
Certain places in my codes, it would be neat to have the ```auto``` functionality and the "range-based for loop". However, my knowledge of the current make procedure is not good enough to tell if this flag would break something or not.

**Comment by bendudson** [comment]
This is planned for the next version of BOUT++, and the "mesh" branch may
already include it (sorry, too lazy to look). After tidying up the current
master, it will be marked as version 3 (for the workshop), and should not
include C++11 features because so many facilities have really old
compilers. After that it's open season on C++11 features like "auto" and
range-for.

**Comment by ZedThree** [comment]
The mesh branch and some other branches off that (parallel-boundaries, for instance) do include C++11 features, but I don't think it's actually in `configure.ac` in those branches. Probably a good idea to add it so that those branches do configure and compile correctly.

Actually, commit 8dc87b38ba9712c4da40a077e1a0b3e5280fdffd in the mesh branch actually changes all loops over the mesh/fields to be `auto` range-based. Show's you what's possible!

**Comment by ZedThree** [comment]
Fixed in next
