### ISSUE TITLE
RGN_NOZ?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#957]
Why should `RGN_NOZ` be invalid?
I would like to use `RGN_NOZ` rather than `RGN_ALL`, in case boundaries in `z` get introduced - such that I don't need to change the code if that happens.

I thus added `RGN_NOZ` to `region` of `Field3D`.

However there is a test to make sure this throws - thus I assume we do not want to change this.

Why?

(This cause #956 to fail)

**Comment by d7919** [comment]
The test just checks it fails because currently this isn't a supported region for Field3D so we want to make sure that requests for invalid regions throw rather than silently falling back to something else.

If `RGN_NOZ` becomes a valid option then this unit test will need to be changed to check that it operates as expected.

**Comment by dschwoerer** [comment]
I thought `RGN_NO?` would simply skip the guard cells in `?` direction.

It works perfectly fine if there are no guard cells in `x` or `y` - then it just does everything.
Why should it be different for `z`?

I would like to use `RGN_NOZ` **before** it becomes different to `RGN_ALL` - so that if boundaries in `z` get introduced - the code will work as it is supposed to work, without having to check every use or `RGN_ALL` and see whether it should be replaced with `RGN_NOZ`.

If you **strongly** feel, that it is a bad idea - please remove `RGN_NOZ` completely, and tell everybody we have no intentions of changing the way the z direction works ...

**Comment by ZedThree** [comment]
I'm not sure what the problem is. There is currently a test to check it throws because currently it's supposed to throw -- it hasn't been implemented, so it would be surprising if it did something. If you change it so that `RGN_NOZ` does do something, change the test to check that it does that something correctly.

The tests aren't necessarily a contract to say "this is the way it will always work", they are more like "this is the way it's currently supposed to work". If we change something and cause a test to fail *that we weren't expecting*, that's a bug. If we change the behaviour, the tests need updating to reflect that new behaviour.

**Comment by dschwoerer** [comment]
I assumed if someone did put the effort into writing a test for that behaviour, it was well thought through. After all the test should make sure the code is doing the right thing - not the code is doing what it is doing ...
But if you don't mind, I will change the test ...

**Comment by d7919** [comment]
The test is really testing that we throw if an unsupported `REGION` is passed -- `RGN_NOZ` was the only `REGION` that's defined but not supported.

**Comment by dschwoerer** [comment]
No I understand - that makes more sense :+1: 
I replaced it with
```
TEST_F(Field3DTest, IterateOverInvalid) {
  Field3D field = 1.0;
  REGION invalid = (REGION) 99999;

  // This is not a valid region for Field3D                                                                   
  EXPECT_THROW(field.region(invalid), BoutException);
}
```
